### Importando bibliotecas




In [23]:
import numpy as np # np es un alias para acortar el uso de numpy
import sys # este paquete maneja fucniones de sistema

###Creando una lista de 10 elementos

In [24]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Consultar el tipo de dato

In [25]:
type(lista1)
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

###Transformando una lista a Array
Recordar que un 'array' es una estructura propia de la librería numpy.

In [26]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Consultando el tipo numérico del array

In [27]:
arreglo.dtype

dtype('int64')

###Crear una lista de solo unos



In [28]:
unos = np.ones(100)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

###Creando una lista de solo ceros


In [29]:
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Lista de Datos Compuestos (Transformando a Array)

In [30]:
lista2 = ['Victor', 2, 5, 6, True]
lista2

['Victor', 2, 5, 6, True]

### Transformando la lista mixta en array
U32 Hace referencia al estándae UNICODE de carácteres

In [31]:
arreglo2 = np.array(lista2)
lista2

['Victor', 2, 5, 6, True]

### Consultando la cantidad de memoria ocupada por estructura (Paquete Sys)

In [32]:
memoria_lista = sys.getsizeof(lista1)
memoria_arreglo = arreglo.nbytes

print(f'Memoria ocupada por la lista: {memoria_lista} bytes')
print(f'Memoria ocupada por el array: {memoria_arreglo} bytes')

Memoria ocupada por la lista: 136 bytes
Memoria ocupada por el array: 80 bytes


### Otro método de Numpy

In [33]:
print('Shape:',          arreglo.shape)         #Dimensiones
print('Dimensions',      arreglo.ndim)          #Número de ejes
print('Tamaño:',         arreglo.size)          #Total de elementos
print('Tipo de dato:',   arreglo.dtype)         #
print('Bytes/elem:',     arreglo.itemsize)      #Tamaño en bytes de cada elemento

Shape: (10,)
Dimensions 1
Tamaño: 10
Tipo de dato: int64
Bytes/elem: 8


### Obteniendo Promedio del Arreglo

In [34]:
promedio = np.mean(lista1)
promedio

np.float64(5.5)

### Transformando el Arreglo de Int a Float
El método astype() transforma los elementos del arreglo a un tipo determinado de dato numérico.

In [35]:
new_arreglo = arreglo.astype(np.float32) #Tipo de número flotante '32'
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [36]:
new_arreglo2 = arreglo.astype(np.float16) #Tipo de número flotante '16'
new_arreglo2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float16)

In [37]:
new_arreglo.dtype


dtype('float32')

### Aplicando el Paquete Random
Se genera una lista de números enteros aleatorios, que van desde el 1 al 100

In [50]:
np.random.rand()

0.6656899964109478

In [38]:
np.random.randint(1,100)

67

In [ ]:
np.random.rand(1,100)

In [48]:
np.random.randint(10)

3

In [ ]:
np.random.rand(10)

In [54]:
np.random.randint(1, 100, 10) #Generando  10 números enteros aleatorioa del 1 al 100

array([78, 67, 50, 79, 64, 83, 26, 68, 73, 66])

In [ ]:
np.random.rand(1, 10, 10)

### Método Arange

In [56]:
arreglo_3 = np.arange(1,11)
arreglo_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])