### Importando bibliotecas




In [1]:
import numpy as np # np es un alias para acortar el uso de numpy
import sys # este paquete maneja fucniones de sistema

###Creando una lista de 10 elementos

In [2]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Consultar el tipo de dato

In [3]:
type(lista1)
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

###Transformando una lista a Array
Recordar que un 'array' es una estructura propia de la librería numpy.

In [4]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Consultando el tipo numérico del array

In [5]:
arreglo.dtype

dtype('int64')

###Crear una lista de solo unos



In [6]:
unos = np.ones(100)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

###Creando una lista de solo ceros


In [7]:
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Lista de Datos Compuestos (Transformando a Array)

In [8]:
lista2 = ['Victor', 2, 5, 6, True]
lista2

['Victor', 2, 5, 6, True]

### Transformando la lista mixta en array
U32 Hace referencia al estándae UNICODE de carácteres

In [9]:
arreglo2 = np.array(lista2)
lista2

['Victor', 2, 5, 6, True]

### Consultando la cantidad de memoria ocupada por estructura (Paquete Sys)

In [10]:
memoria_lista = sys.getsizeof(lista1)
memoria_arreglo = arreglo.nbytes

print(f'Memoria ocupada por la lista: {memoria_lista} bytes')
print(f'Memoria ocupada por el array: {memoria_arreglo} bytes')

Memoria ocupada por la lista: 136 bytes
Memoria ocupada por el array: 80 bytes


### Otro método de Numpy

In [11]:
print('Shape:',          arreglo.shape)         #Dimensiones
print('Dimensions',      arreglo.ndim)          #Número de ejes
print('Tamaño:',         arreglo.size)          #Total de elementos
print('Tipo de dato:',   arreglo.dtype)         #
print('Bytes/elem:',     arreglo.itemsize)      #Tamaño en bytes de cada elemento

Shape: (10,)
Dimensions 1
Tamaño: 10
Tipo de dato: int64
Bytes/elem: 8


### Obteniendo Promedio del Arreglo

In [12]:
promedio = np.mean(lista1)
promedio

np.float64(5.5)

### Transformando el Arreglo de Int a Float
El método astype() transforma los elementos del arreglo a un tipo determinado de dato numérico.

In [13]:
new_arreglo = arreglo.astype(np.float32) #Tipo de número flotante '32'
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [14]:
new_arreglo2 = arreglo.astype(np.float16) #Tipo de número flotante '16'
new_arreglo2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float16)

In [15]:
new_arreglo.dtype


dtype('float32')

### Aplicando el Paquete Random
Se genera una lista de números enteros aleatorios, que van desde el 1 al 100

In [16]:
np.random.rand()

0.9421194883354532

In [17]:
np.random.randint(1,100)

62

In [18]:
np.random.rand(1,100)

array([[0.26931456, 0.83608301, 0.44705771, 0.97408492, 0.82331367,
        0.01347606, 0.90159228, 0.88171437, 0.39442415, 0.95447578,
        0.22816924, 0.69486853, 0.90354588, 0.55170442, 0.6084166 ,
        0.25434597, 0.74111213, 0.81025289, 0.84678044, 0.42710492,
        0.75111193, 0.89630789, 0.36587475, 0.47622779, 0.61142268,
        0.391645  , 0.02818447, 0.80679731, 0.28454965, 0.13943221,
        0.73740386, 0.14950296, 0.04413305, 0.36236923, 0.54259794,
        0.25596727, 0.57103266, 0.91412458, 0.30557117, 0.16429434,
        0.89948274, 0.58740847, 0.11520256, 0.44013751, 0.73368045,
        0.21739054, 0.41394877, 0.71919373, 0.06781124, 0.7584507 ,
        0.17272432, 0.91229657, 0.33913804, 0.54197849, 0.34513684,
        0.80850973, 0.39669813, 0.05525006, 0.64632442, 0.31912109,
        0.60989836, 0.06380586, 0.09855448, 0.74827193, 0.51014358,
        0.20176892, 0.07499105, 0.36826017, 0.29058092, 0.97675739,
        0.12009679, 0.44343737, 0.11146387, 0.97

In [19]:
np.random.randint(10)

7

In [20]:
np.random.rand(10)

array([0.52681002, 0.54227723, 0.32999392, 0.00692622, 0.1501802 ,
       0.07780273, 0.06003929, 0.78424656, 0.59333871, 0.29641801])

In [21]:
np.random.randint(1, 100, 10) #Generando  10 números enteros aleatorioa del 1 al 100

array([ 5, 31, 69, 89, 36, 97, 21, 14, 24, 33], dtype=int32)

In [22]:
np.random.rand(1, 10, 10)

array([[[0.69908137, 0.95113638, 0.52062987, 0.11584215, 0.83203819,
         0.34020026, 0.64594656, 0.77198855, 0.86475398, 0.41229521],
        [0.70434931, 0.58608808, 0.12677323, 0.32909126, 0.29868062,
         0.32420314, 0.85340815, 0.74659339, 0.78107763, 0.57807851],
        [0.58033634, 0.93163493, 0.15954886, 0.53341303, 0.3966523 ,
         0.96724406, 0.33011784, 0.23109722, 0.29393688, 0.14779253],
        [0.03560371, 0.91675044, 0.62776188, 0.19507894, 0.16302211,
         0.16635625, 0.92835632, 0.75701655, 0.16657756, 0.41015213],
        [0.1786463 , 0.7855941 , 0.55274285, 0.0494913 , 0.30774467,
         0.61667639, 0.4406111 , 0.11110512, 0.84343788, 0.87002994],
        [0.74202637, 0.37284539, 0.22982525, 0.66757224, 0.24354468,
         0.11998175, 0.43851699, 0.80773286, 0.79566514, 0.85239406],
        [0.58739337, 0.93344094, 0.27304726, 0.72303953, 0.98766021,
         0.63073479, 0.2946691 , 0.87120677, 0.91024587, 0.22002136],
        [0.36437495, 0.1404

### Método Arange

In [23]:
arreglo_3 = np.arange(1,11)
arreglo_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])